spring.application.name=Hotel

spring.datasource.url=jdbc:postgresql://localhost:5432/Hotel
spring.datasource.username=postgres
spring.datasource.password=ihsanmee
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
